修改变量

diff --git a/docker-php-entrypoint b/docker-php-entrypoint
--- a/docker-php-entrypoint
+++ b/docker-php-entrypoint
@@ -33,7 +33,7 @@ TIMEZONE=${TIMEZONE-Asia/Shanghai}
 POST_MAX_SIZE=${POST_MAX_SIZE-100M}
 UPLOAD_MAX_FILESIZE=${UPLOAD_MAX_FILESIZE-50M}
 MAX_EXECUTION_TIME=${MAX_EXECUTION_TIME-5}
-PHP_FPM_CONF=${PHP_FPM_CONF-${INSTALL_DIR}/etc/php-fpm.conf}
+PHP_FPM_CONF=${PHP_FPM_CONF-${PHP_INI_DIR}/php-fpm.conf}
 PHP_FPM_PID=${PHP_FPM_PID-${INSTALL_DIR}/var/run/php-fpm.pid}
 PHP_DISABLE_FUNCTIONS=${PHP_DISABLE_FUNCTIONS:-passthru,exec,system,chroot,chgrp,chown,shell_exec,proc_open,proc_get_status,ini_alter,ini_restore,dl,openlog,syslog,readlink,symlink,popepassthru,stream_socket_server,fsocket,popen}
 DISPLAY_ERROES=${DISPLAY_ERROES:-Off}
@@ -66,22 +66,22 @@ set -- "$@" --pid ${PHP_FPM_PID}
 
 sed -i "s@\$HOSTNAME@$HOSTNAME@" ${PHP_FPM_CONF}
 
-sed -i "s@^memory_limit.*@memory_limit = ${MEM_LIMIT}M@" ${INSTALL_DIR}/etc/php.ini
-sed -i "s@^output_buffering =@output_buffering = On\noutput_buffering =@" ${INSTALL_DIR}/etc/php.ini
-sed -i "s@^;cgi.fix_pathinfo.*@cgi.fix_pathinfo=0@" ${INSTALL_DIR}/etc/php.ini
-sed -i "s@^short_open_tag = Off@short_open_tag = On@" ${INSTALL_DIR}/etc/php.ini
-sed -i "s@^expose_php = On@expose_php = ${EXPOSE_PHP}@" ${INSTALL_DIR}/etc/php.ini
-sed -i "s@^request_order.*@request_order = \"CGP\"@" ${INSTALL_DIR}/etc/php.ini
-sed -i "s@^;date.timezone.*@date.timezone = ${TIMEZONE}@" ${INSTALL_DIR}/etc/php.ini
-sed -i "s@^post_max_size.*@post_max_size = ${POST_MAX_SIZE}@" ${INSTALL_DIR}/etc/php.ini
-sed -i "s@^upload_max_filesize.*@upload_max_filesize = ${UPLOAD_MAX_FILESIZE}@" ${INSTALL_DIR}/etc/php.ini
-sed -i "s@^max_execution_time.*@max_execution_time = ${MAX_EXECUTION_TIME}@" ${INSTALL_DIR}/etc/php.ini
-sed -i "s@^disable_functions.*@disable_functions = ${PHP_DISABLE_FUNCTIONS}@" ${INSTALL_DIR}/etc/php.ini
-sed -i "s@^;sendmail_path.*@sendmail_path = /usr/sbin/sendmail -t -i@" ${INSTALL_DIR}/etc/php.ini
-sed -i "s@^display_errors.*@display_errors = ${DISPLAY_ERROES}@" ${INSTALL_DIR}/etc/php.ini
+sed -i "s@^memory_limit.*@memory_limit = ${MEM_LIMIT}M@" ${PHP_INI_DIR}/php.ini
+sed -i "s@^output_buffering =@output_buffering = On\noutput_buffering =@" ${PHP_INI_DIR}/php.ini
+sed -i "s@^;cgi.fix_pathinfo.*@cgi.fix_pathinfo=0@" ${PHP_INI_DIR}/php.ini
+sed -i "s@^short_open_tag = Off@short_open_tag = On@" ${PHP_INI_DIR}/php.ini
+sed -i "s@^expose_php = On@expose_php = ${EXPOSE_PHP}@" ${PHP_INI_DIR}/php.ini
+sed -i "s@^request_order.*@request_order = \"CGP\"@" ${PHP_INI_DIR}/php.ini
+sed -i "s@^;date.timezone.*@date.timezone = ${TIMEZONE}@" ${PHP_INI_DIR}/php.ini
+sed -i "s@^post_max_size.*@post_max_size = ${POST_MAX_SIZE}@" ${PHP_INI_DIR}/php.ini
+sed -i "s@^upload_max_filesize.*@upload_max_filesize = ${UPLOAD_MAX_FILESIZE}@" ${PHP_INI_DIR}/php.ini
+sed -i "s@^max_execution_time.*@max_execution_time = ${MAX_EXECUTION_TIME}@" ${PHP_INI_DIR}/php.ini
+sed -i "s@^disable_functions.*@disable_functions = ${PHP_DISABLE_FUNCTIONS}@" ${PHP_INI_DIR}/php.ini
+sed -i "s@^;sendmail_path.*@sendmail_path = /usr/sbin/sendmail -t -i@" ${PHP_INI_DIR}/php.ini
+sed -i "s@^display_errors.*@display_errors = ${DISPLAY_ERROES}@" ${PHP_INI_DIR}/php.ini
 
 if [[ "${OPCACHE}" =~ [eE][nN][aA][bB][lL][eE] ]]; then
-	cat > ${INSTALL_DIR}/etc/php.d/10-opcache.ini <<-EOF
+	cat > ${PHP_INI_DIR}/php.d/10-opcache.ini <<-EOF
 		[opcache]
 		zend_extension=opcache.so
 		opcache.enable=1
@@ -97,14 +97,14 @@ if [[ "${OPCACHE}" =~ [eE][nN][aA][bB][lL][eE] ]]; then
 fi
 
 if [[ "${EVENT}" =~ [eE][nN][aA][bB][lL][eE] ]]; then
-	cat > ${INSTALL_DIR}/etc/php.d/10-event.ini <<-EOF
+	cat > ${PHP_INI_DIR}/php.d/10-event.ini <<-EOF
 		extension=event.so
 	EOF
 fi
 
 if [[ "$MEMCACHE" =~ ^[eE][nN][aA][bB][lL][eE]$ ]]; then
-	echo 'extension=memcache.so' > ${INSTALL_DIR}/etc/php.d/10-memcache.ini
-	cat > ${INSTALL_DIR}/etc/php.d/10-memcached.ini <<-EOF
+	echo 'extension=memcache.so' > ${PHP_INI_DIR}/php.d/10-memcache.ini
+	cat > ${PHP_INI_DIR}/php.d/10-memcached.ini <<-EOF
 		[memcached]
 		extension=memcached.so
 		memcached.use_sasl=1
@@ -112,14 +112,14 @@ if [[ "$MEMCACHE" =~ ^[eE][nN][aA][bB][lL][eE]$ ]]; then
 fi
 
 if [[ "$REDIS" =~ ^[eE][nN][aA][bB][lL][eE]$ ]]; then
-	cat > ${INSTALL_DIR}/etc/php.d/10-redis.ini <<-EOF
+	cat > ${PHP_INI_DIR}/php.d/10-redis.ini <<-EOF
 		[redis]
 		extension=redis.so
 	EOF
 fi
 
 if [[ "${SWOOLE}" =~ ^[eE][nN][aA][bB][lL][eE]$ ]]; then
-	cat > ${INSTALL_DIR}/etc/php.d/10-swoole.ini <<-EOF
+	cat > ${PHP_INI_DIR}/php.d/10-swoole.ini <<-EOF
 		[swoole]
 		extension=swoole.so
 	EOF
@@ -127,7 +127,7 @@ fi
 
 if [[ "${XDEBUG}" =~ [eE][nN][aA][bB][lL][eE] ]]; then
 	if [[ "${XDEBUG_DEFAULT_CONF}" =~ [eE][nN][aA][bB][lL][eE] ]]; then
-		cat >> ${INSTALL_DIR}/etc/php.d/10-xdebug.ini <<-EOF
+		cat >> ${PHP_INI_DIR}/php.d/10-xdebug.ini <<-EOF
 			zend_extension="xdebug.so"
 			xdebug.remote_enable=on
 			;远程调试开关
@@ -156,9 +156,9 @@ if [[ "${XDEBUG}" =~ [eE][nN][aA][bB][lL][eE] ]]; then
 			;xdebug.idekey=netbeans
 			;调试使用的关键字，发起IDE上的idekey应该和这里配置的idekey一致，不一致则无效
 		EOF
-	elif [[ ! -f ${INSTALL_DIR}/etc/php.d/10-xdebug.ini ]]; then
-		echo >&2 "error:  missing Can't found ${INSTALL_DIR}/etc/php.d/10-xdebug.ini"
-		echo >&2 "Did you forget to add -v /xdebug_config_file:${INSTALL_DIR}/etc/php.d/10-xdebug.ini"
+	elif [[ ! -f ${PHP_INI_DIR}/php.d/10-xdebug.ini ]]; then
+		echo >&2 "error:  missing Can't found ${PHP_INI_DIR}/php.d/10-xdebug.ini"
+		echo >&2 "Did you forget to add -v /xdebug_config_file:${PHP_INI_DIR}/php.d/10-xdebug.ini"
 		exit 1
 	fi
 fi
